kind: Deployment
apiVersion: apps/v1
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:

      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
