kind: Deployment
apiVersion: apps/v1
metadata:
  name: pets-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pets-api
  template:
    metadata:
      labels:
        app: pets-api
    spec:
      containers:
        - name: pets-api
          image: elizaochoa86/pets:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_HOST
              value: 172.18.0.1