apiVersion: v1
kind: Service
metadata:
  name: pets-api-service
spec:
  type: NodePort
  selector:
    app: pets-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007