

CREATE TABLE species (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  description varchar(250) NOT NULL
);


CREATE TABLE race (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(250) NOT NULL,
  description varchar(500) DEFAULT NULL,
  species_id int NOT NULL,
  CONSTRAINT race_ibfk_1 FOREIGN KEY (species_id) REFERENCES species (id)
);

CREATE TABLE pet (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  age int NOT NULL,
  hasChip bit(1) NOT NULL,
  vaccinated bit(1) NOT NULL,
  race int NOT NULL,
  CONSTRAINT pet_ibfk_4 FOREIGN KEY (race) REFERENCES race (id)
);

